### ISSUE TITLE
Improve handling of corrupt state file

### ISSUE THREAD

**Issue by pcbaldwin** [eglooca/netify-fwa#1]
The netify-fwa daemon will refuse to start if there's a corrupt /var/lib/netify-fwa/state.dat

`Sep 22 10:35:24 fwcs.online.linux netify-fwa[8343]: Exception: netify-fwa.php:285: Unable to decode state file: /var/lib/netify-fwa/state.dat`

It would be nice to catch this issue and resolve it.

**Comment by dsokoloski** [comment]
State file support removed entirely in commit: 57763b89ec0514d9626da9e54c5f845b5ce8feaa
